//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeeMVC_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public long Id { get; set; }
        public long Author { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime PostModified { get; set; }
        public string Contents { get; set; }
        public string Title { get; set; }
        public string Excerpt { get; set; }
        public string Status { get; set; }
        public string PostName { get; set; }
        public string Guid { get; set; }
        public int TermsId { get; set; }
        public string PostType { get; set; }
    }
}
