//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeeMVC_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermTaxonomy
    {
        public long TermTaxonomyId { get; set; }
        public long TermId { get; set; }
        public string Taxonomy { get; set; }
        public string Description { get; set; }
        public Nullable<long> Parent { get; set; }
        public Nullable<long> Count { get; set; }
    }
}
