//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeeMVC_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermRelationship
    {
        public long ObjectId { get; set; }
        public long TermTaxonomyId { get; set; }
        public Nullable<int> TermOrder { get; set; }
    }
}
