//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeeMVC_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public Nullable<int> TermGroup { get; set; }
    }
}
